const ROOT = __dirname;
const PYTHON = `${ROOT}/.venv/bin/python`;
const LOAD_ENV = "set -a; [ -f .env ] && . ./.env; set +a";
const LIMITLESS_ENV = [
  "LIMITLESS_OWNER_ID=\${LIMITLESS_OWNER_ID}",
  "LIMITLESS_MAKER_ADDRESS=\${LIMITLESS_MAKER_ADDRESS}",
  "LIMITLESS_FEE_RATE_BPS=\${LIMITLESS_FEE_RATE_BPS:-300}",
  "LIMITLESS_SIGNATURE_TYPE=\${LIMITLESS_SIGNATURE_TYPE:-0}",
  "LIMITLESS_FUNDING_ALLOW_UNHEDGED=\${LIMITLESS_FUNDING_ALLOW_UNHEDGED:-1}",
].join(" ");

module.exports = {
  apps: [
    {
      // Read-only trade-flow recorder + wallet scorer. No keys, no orders.
      name: "limitless-hl-flow",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `"${PYTHON}" -m limitless_hl.flow_recorder --loop-seconds 60 --score-every-loops 15 --db tmp/limitless_hl/flow.sqlite3 --scores-out tmp/limitless_hl/shark_scores.json --jsonl-out tmp/limitless_hl/flow_recorder.jsonl`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-live",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; ${LIMITLESS_ENV} "${PYTHON}" -m limitless_hl.daemon --live-armed --intervals 15m --sides UP,DOWN --slice-score-file tmp/limitless_hl/evaluation_report_live.json --slice-min-n 3 --slice-min-roi 0.02 --slice-min-win-rate 0.25 --slice-live-min-n 4 --slice-live-min-roi 0.0 --shadow-graduate --shadow-min-n 20 --shadow-min-roi 0.10 --shadow-min-win-rate 0.52 --scoring-live --score-min 2.0 --min-price 0.35 --exclude-price-band 0.45 0.55 --max-edge 0.12 --max-trades-per-hour 6 --loss-cooldown-losses 3 --loss-cooldown-seconds 1800 --polymarket-gate-threshold 0.10 --score-base-stake-usdc 1 --score-max-stake-usdc 1 --hl-bot-status-file /opt/hyperliquid-bot/hl_bot_status.json --min-edge 0.03 --max-price 0.70 --min-seconds-to-expiry 300 --stake-usdc 1 --max-daily-loss-usdc 3 --max-open-markets 2 --loop-seconds 30 --scan-error-backoff-seconds 120 --stop-on-insufficient-collateral --book-log tmp/limitless_hl/book_snapshots.jsonl --jsonl-out tmp/limitless_hl/daemon_trades.jsonl`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-learner",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `"${PYTHON}" -m limitless_hl.learner --db tmp/limitless_hl/learner.sqlite3 --log tmp/limitless_hl/daemon_trades.jsonl --log tmp/limitless_hl/daemon_shadow.jsonl --log tmp/limitless_hl/funding_trades.jsonl --log tmp/limitless_hl/funding_dry.jsonl --log tmp/limitless_hl/maker_trades.jsonl --log tmp/limitless_hl/copy_shadow.jsonl --log tmp/limitless_hl/copy_live.jsonl --log tmp/limitless_hl/band_shadow.jsonl --log tmp/limitless_hl/band_live.jsonl --seed-report data/evaluation_report_strict.json --report-out tmp/limitless_hl/evaluation_report_live.json --loop-seconds 45`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-claimer",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; LIMITLESS_MAKER_ADDRESS=\${LIMITLESS_MAKER_ADDRESS} "${PYTHON}" -m limitless_hl.claimer --live --log-dir tmp/limitless_hl --loop-seconds 60 --jsonl-out tmp/limitless_hl/claims.jsonl`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-funding-dry",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; ${LIMITLESS_ENV} "${PYTHON}" -m limitless_hl.funding_daemon --min-stake-usdc 1 --first-spike-only --loop-seconds 60 --min-seconds-to-expiry 120 --jsonl-out tmp/limitless_hl/funding_dry.jsonl`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-shadow",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; ${LIMITLESS_ENV} "${PYTHON}" -m limitless_hl.daemon --intervals 1m,5m,15m,1h,1d,1w --sides UP,DOWN --scoring-live --slice-score-file tmp/limitless_hl/evaluation_report_live.json --slice-min-n 0 --slice-min-roi -1.0 --slice-min-win-rate 0.0 --score-min 0.0 --score-base-stake-usdc 1 --score-max-stake-usdc 1 --hl-bot-status-file /opt/hyperliquid-bot/hl_bot_status.json --min-edge 0.0 --max-price 0.95 --min-seconds-to-expiry 45 --stake-usdc 1 --max-daily-loss-usdc 999 --max-open-markets 100 --loop-seconds 45 --scan-error-backoff-seconds 180 --jsonl-out tmp/limitless_hl/daemon_shadow.jsonl`,
      ],
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 50,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-copy-shadow",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; ${LIMITLESS_ENV} "${PYTHON}" -m limitless_hl.copy_shadow --loop-seconds 8 --live-allowed --live-stake-usdc 1 --live-max-per-day 30 --live-daily-loss-stop 3 --rank-seconds 900 --min-markets 10 --min-roi 0.05 --min-pnl 20 --max-avg-price 0.85 --min-seconds-to-expiry 120 --max-chase 0.06 --jsonl-out tmp/limitless_hl/copy_shadow.jsonl`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-gatekeeper",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; "${PYTHON}" -m limitless_hl.gatekeeper --loop-seconds 600 --min-n 100 --manage-model-pm2 --jsonl-out tmp/limitless_hl/gatekeeper.jsonl`,
      ],
      autorestart: true,
      restart_delay: 15000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-ev-model",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `"${PYTHON}" -m limitless_hl.ev_model --interval-seconds 21600 --min-n 500 --min-auc 0.55`,
      ],
      autorestart: true,
      restart_delay: 60000,
      max_restarts: 10,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-band",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `"${PYTHON}" -m limitless_hl.band_taker --loop-seconds 10 --band-lo 0.58 --band-hi 0.74 --ste-lo 120 --ste-hi 300 --intervals 5m,15m --jsonl-out tmp/limitless_hl/band_shadow.jsonl`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-tg",
      cwd: ROOT,
      script: "bash",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; "${PYTHON}" -m limitless_hl.tgbot`,
      ],
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 20,
      time: true,
      vizion: false,
    },
    {
      name: "limitless-hl-maker",
      script: "/usr/bin/bash",
      interpreter: "none",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; ${LIMITLESS_ENV} "${PYTHON}" -m limitless_hl.maker --live-armed --intervals 1h --symbols AUTO --margin 0.05 --quote-size-usdc 1.5 --max-total-locked-usdc 8 --max-inventory-usdc 4 --max-markets 3 --min-seconds-to-expiry 600 --loop-seconds 30 --jsonl-out tmp/limitless_hl/maker_trades.jsonl`,
      ],
      cwd: ROOT,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 15000,
    },
    {
      name: "limitless-hl-exiter",
      script: "/usr/bin/bash",
      interpreter: "none",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; ${LIMITLESS_ENV} "${PYTHON}" -m limitless_hl.exiter --live-armed --epsilon 0.015 --loop-seconds 20 --jsonl-out tmp/limitless_hl/exiter_trades.jsonl`,
      ],
      cwd: ROOT,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 15000,
    },
    {
      name: "limitless-hl-calibrator",
      script: "/usr/bin/bash",
      interpreter: "none",
      args: [
        "--noprofile", "--norc", "-c",
        `${LOAD_ENV}; "${PYTHON}" -m limitless_hl.calibrator --interval-seconds 21600 --params-out tmp/limitless_hl/pricing_params.json`,
      ],
      cwd: ROOT,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 60000,
      kill_timeout: 15000,
    },
  ],
};
